# /etc/portage/make.conf
# Security-first Gentoo configuration
# Target: ThinkPad T470 (Intel Kaby Lake)
# Init: systemd-free (OpenRC / s6 / runit)
# FS: Btrfs + LUKS
# MAC: SELinux

############################
# Architecture / Toolchain
############################
CHOST="x86_64-pc-linux-gnu"
ABI_X86="64"
COMMON_FLAGS="-O2 -pipe -march=native -mtune=native -fstack-protector-strong -fstack-clash-protection -fcf-protection=full -fno-plt -D_FORTIFY_SOURCE=3"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack"
RUSTFLAGS="-C opt-level=2 -C target-cpu=native"

############################
# Build Behaviour
###########################
PORTAGE_NICENESS=10
MAKEOPTS="-j3 -l12.5"
EMERGE_DEFAULT_OPTS="--ask --jobs=1 --load-average=1 --backtrack=50 --with-bdeps=y --quiet-build=y"

############################
# Portage Features
############################
FEATURES="sandbox ipc-sandbox network-sandbox pid-sandbox usersandbox \
          strict ccache parallel-fetch buildpkg binpkg-multi-instance \
          splitdebug compressdebug \
	  preserve-libs -autounmask -autounmask-write" 

############################
# Mirrors
############################
GENTOO_MIRRORS="https://mirror.aarnet.edu.au/pub/gentoo"

############################
# USE flags (global)
############################
USE="btrfs crypt luks efi pie ssp selinux audit \
hardened seccomp caps acl xattr pam static static-libs \
-bindist -doc -lto -llvm -valgrind -rpath \
-multilib -32bit -systemd -elogind -kmod"

############################
# CPU / Hardware
############################
CPU_FLAGS_X86="aes avx avx2 fma3 mmx sse sse2 sse3 sse4_1 sse4_2"
VIDEO_CARDS="intel"
INPUT_DEVICES="libinput"

############################
# SELinux
############################
#POLICY_TYPES="strict"
#SELINUXTYPE="strict"

############################
# Python / Perl
############################
PYTHON_TARGETS="python3_12"
PYTHON_SINGLE_TARGET="python3_12"

############################
# Licensing / Security hygiene
############################
ACCEPT_KEYWORD="amd64"
ACCEPT_LICENSE="@FREE"


############################
# Disk / FS /tmp
############################
PORTAGE_TMPDIR="/var/tmp/portage"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"
CCACHE_DIR="/var/tmp/ccache"
CARGO_HOME="/var/cache/cargo"
RUSTUP_HOME="/usr/lib/rust"
############################
# ccache settings
############################
CCACHE_SIZE="50G"
CCACHE_COMPARE="1"
CCACHE_COMPRESSLEVEL="6"

GRUB_PLATFORMS="efi-64"



############################
# Locale
############################
LC_MESSAGES="C"

############################
# Kernel / Init awareness
############################
# No systemd integration assumed
# UKI / EFI-stub handled outside Portage

